name: Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/docs/**"
      - ".github/workflows/docker-hub-description.yml"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    name: Docker Hub Update
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Docker Hub Description ZSHbuntu
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/zshbuntu
          short-description: "Your Ultimate Ubuntu Image with Zsh Magic!"
          readme-filepath: "./zshbuntu/docs/README.md"

      - name: Docker Hub Description ZSHmazon
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/zshmazon
          short-description: "Your Ultimate AmazonLinux2023 Image with Zsh Magic!"
          readme-filepath: "./zshmazon/docs/README.md"