name: Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/docs/**"
      - ".github/workflows/docker-hub-description.yml"

jobs:
  prepare-folders:
    runs-on: ubuntu-latest
    name: Prepare folders
    outputs:
      directories: ${{ steps.list_folders.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - id: list_folders
        name: List folders
        run: |
          directory_quoted_and_comma=$(find . -type f \( -name Dockerfile -o -path 'docs/README.md' -o -path 'docs/short_description.txt' \) -exec dirname {} \; | sort -u | awk 'BEGIN { ORS = "," } { gsub(/^\.\//, ""); print "\"" $0 "\"" }' | sed 's/,$//' )
          echo "directories=[${directory_quoted_and_comma}]" >> "$GITHUB_OUTPUT"
          echo "::notice title=directories::[${directory_quoted_and_comma}]"

  docker-hub:
    needs: prepare-folders
    runs-on: ubuntu-latest
    name: Docker Hub Update
    strategy:
      matrix:
        directories: ${{ fromJSON(needs.prepare-folders.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - id: read_files
        name: Read files
        run: |
          echo "short_description=$(cat ./${{ matrix.directories }}/docs/short_description.txt)" >> $GITHUB_OUTPUT

      - name: Description Update ${{ matrix.directories }}
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.directories }}
          short-description: ${{ steps.read_files.outputs.short_description }}
          readme-filepath: "./${{ matrix.directories }}/docs/README.md"